# Generated by Django 4.0.3 on 2022-03-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='total_amount',
        ),
    ]
