# Generated by Django 4.0.3 on 2022-03-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_order_info_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Info',
        ),
    ]
